version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: huginn:master    # Required. Must be in the same fork network.
    mergeMethod: hardreset  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  - base: slim
    upstream: master        # Required. Can be a branch in the same forked repo.
label: ":arrow_heading_down: pull"  # Optional
